### ISSUE TITLE
Understanding E-Mail Settings, Subject & Body structure

### ISSUE THREAD

**Issue by ertankucukoglu** [hiyohiyo/CrystalDiskInfo#105]
Hello,

I have a NVMe drive. It has "Critical Warning", "Available Spare" and "Percentage used" I want to have these information e-mailed to me when any of them changed.
![image](https://user-images.githubusercontent.com/14805520/101292151-c928ca00-381e-11eb-8c9a-e14795711320.png)

I simply could not understand by reading examples provided on manual. 
https://crystalmark.info/en/software/crystaldiskinfo/crystaldiskinfo-alert-mail/

Do they already contain that data I want? If I have to add something in them and what it should be?

To be honest, I did not have a clear understanding of the structure for subject and body. I fail to find any other source.

I appreciate any help.

Thanks & Regards,
Ertan

**Comment by hiyohiyo** [comment]
Critical Warning: No support
Available Spare: No support
Percentage used: No support

I will add Critical Warning support for CrystalDiskInfo 8.9.0.
Others will be supported for future release.

**Comment by ertankucukoglu** [comment]
Version 8.10.0 is released.

It is still not listed "Critical Warning" in below link. Is it because web site not updated, yet?
https://crystalmark.info/en/software/crystaldiskinfo/crystaldiskinfo-event-log/

Thanks for clarification.

Regards,
Ertan Küçükoğlu

**Comment by hiyohiyo** [comment]
Sorry, I did not add individual support for Critical Warning.

CrystalDiskInfo reports "Bad" health status when Critical Warning sets a flag.
