### ISSUE TITLE
SCSI/ATA Translation to SAT'Problem

### ISSUE THREAD

**Issue by lwei2** [hiyohiyo/CrystalDiskInfo#111]
Hi, hiyohiyo, In SCSI/ATA Translation to SAT,why comment out the sptwb.databuf [510]! = 0 xa5?

**Comment by hiyohiyo** [comment]
A part of USB-SATA bridge chip returns "sptwb.databuf [510] != 0xA5".
If it checks strictly, it may not display anything...

**Comment by lwei2** [comment]
> A part of USB-SATA bridge chip returns "sptwb.databuf [510] != 0xA5".
> If it checks strictly, it may not display anything...
Hi,hiyohiyo,when  (I CrystalDiskInfo was used to read the hard disk of USBS-SATA bridge chip, the phenomenon of stalling appeared.Therefore, I would like to ask what might be the cause of this problem?

**Comment by lwei2** [comment]
> A part of USB-SATA bridge chip returns "sptwb.databuf [510] != 0xA5".
> If it checks strictly, it may not display anything...
Hi,hiyohiyo,when I used CrystalDiskInfo to read the hard disk of USBS-SATA bridge chip, the phenomenon of stalling appeared.Therefore, I would like to ask what might be the cause of this problem?
