### ISSUE TITLE
Adding to Microsoft Store?

### ISSUE THREAD

**Issue by nathanielcwm** [hiyohiyo/CrystalDiskInfo#112]
I see that CrystalDiskMark is already on the Microsoft Store [here](https://www.microsoft.com/en-us/p/crystaldiskmark/9nblggh4z6f2).

Would it be hard to also put DiskInfo onto the store?  *idk if it's UWP or Win32*

**Comment by hiyohiyo** [comment]
Basically, Microsoft Store does not support apps which require administrative privileges.
