### ISSUE TITLE
Silent update

### ISSUE THREAD

**Issue by ajtak-angelus** [hiyohiyo/CrystalDiskInfo#116]
Hi,
unfortunately it is not possible to update as silent application. The switch /CLOSEAPPLICATIONS neither /FORCECLOSEAPPLICATIONS does not work. CDI run as Resident and does not quit during update Please fix this.
thank you for your wonderful work!

**Comment by hiyohiyo** [comment]
Sorry, CrystalDiskInfo does not support silent update.
Please close CrystalDiskInfo before updating.
