### ISSUE TITLE
CrystalDiskInfo 8.12.2 Shows no drives

### ISSUE THREAD

**Issue by JKZuchel** [hiyohiyo/CrystalDiskInfo#125]
Hello, I have installed crystal disk info 8.12.2, the issue is that it won’t show any internal disks, but it does recognize external drives.
All my drives are connected through SATA to my motherboard (Asus Prime X570-P)
Please tell me If there is any other info required.
System info:
Windows 10 Pro (21H1 - 19043.1081)
AMD R5 3600XT (Cpu)
AMD rx570 (Gpu)
*Picture 1 has no external drives connected - Picture 2 has 1 external drive connected

![Picture 1](https://user-images.githubusercontent.com/65378864/124198392-8e2e0280-da9e-11eb-9fdb-6b8c45807d5d.png)
![Picture 2](https://user-images.githubusercontent.com/65378864/124198396-8f5f2f80-da9e-11eb-9fef-dc14d6c3a7c2.png)

**Comment by JKZuchel** [comment]
I like to comment that I have updated the bios for the motherboard, the version installed now is 4002 details. [here](https://www.asus.com/us/Motherboards-Components/Motherboards/All-series/PRIME-X570-P/HelpDesk_BIOS/)

**Comment by beerisgood** [comment]
Did you use software like AV which block program features?
Windows Ransomware protection can also block stuff too, but you get a message about.

**Comment by JKZuchel** [comment]
> 
> 
> Did you use software like AV which block program features?
> Windows Ransomware protection can also block stuff too, but you get a message about.

Could you explain more?

**Comment by mikunya** [comment]
same problem with the x570 motherboard. 
X570 I AORUS PRO WIFI

**Comment by hiyohiyo** [comment]
CrystalDiskInfo does not support AMD AHCI/NVMe/RAID driver.
Please use Microsoft AHCI/NVMe driver.
