### ISSUE TITLE
About software starting speed

### ISSUE THREAD

**Issue by haobinnan** [hiyohiyo/CrystalDiskInfo#154]
I found that the new version starts very slowly (about a year). It is not as fast as the previous version.

**Comment by hiyohiyo** [comment]
Sorry, too late reply.

I would like you to send DiskInfo.log of slow version and fast version.

How to create DiskInfo.log.
https://crystalmark.info/en/software/crystaldiskinfo/crystaldiskinfo-contact/

**Comment by haobinnan** [comment]
00000000 8.13.0
00000000 2021/11/26
00000016 CreateMutex
00000032 AfxOleInit()
00000032 AfxOleGetMessageFilter()->SetMessagePendingDelay
00000047 AfxOleGetMessageFilter()->EnableNotRespondingDialog(FALSE)
00000047 AfxOleGetMessageFilter()->EnableBusyDialog(FALSE)
00000047 CDiskInfoDlg::CDiskInfoDlg - START
00000047 CDiskInfoDlg::CDiskInfoDlg - CENTER
00000047 CDiskInfoDlg::CDiskInfoDlg - END
00000047 dlg.DoModal()
00000422 InitAta
00000422 CAtaSmart::Init WMI on - Start
00000422 CoInitializeSecurity()
00000438 CoCreateInstance()
00000438 ConnectServer()
00000453 CoSetProxyBlanket()
00000453 OK:WMI Init
00002250 OK:Win32_IDEController
00002282 OK:Win32_SCSIController
00002282 --ControllerMap--
 + Intel(R) 300 Series Chipset Family SATA AHCI Controller [ATA]
   - PIONEER DVD-RW  DVR-219L
   - ST2000DM008-2FR102
   - ST4000NM000A-2HZ100
 - Microsoft 存储空间控制器 [SCSI]
 + Intel(R) SSD Pro 7600p/760p/E 6100p Series [SCSI]
   - INTEL SSDPEKKW256G8

00002297 OK:Win32_USBController
00002297 WakeUp(0)
00002313 WakeUp(1)
00002594 WakeUp(2)
00002594 DoIdentifyDeviceCsmi
00002610 asi.Model.IsEmpty() || asi.FirmwareRev.IsEmpty()
00002610 DoIdentifyDeviceCsmi
00002610 GetSmartAttributeCsmi
00002657 FillSmartData
00002657 GetSmartAttributeCsmi
00002688 FillSmartData
00002688 GetSmartThresholdCsmi
00002688 FillSmartThreshold
00002688 DoIdentifyDeviceCsmi
00002703 asi.Model.IsEmpty() || asi.FirmwareRev.IsEmpty()
00002703 DoIdentifyDeviceCsmi
00002703 asi.Model.IsEmpty() || asi.FirmwareRev.IsEmpty()
00002703 DoIdentifyDeviceCsmi
00002703 GetSmartAttributeCsmi
00002703 FillSmartData
00002703 GetSmartAttributeCsmi
00002703 FillSmartData
00002703 GetSmartThresholdCsmi
00002719 FillSmartThreshold
00002719 DoIdentifyDeviceCsmi
00002719 asi.Model.IsEmpty() || asi.FirmwareRev.IsEmpty()
00002719 DO:SELECT * FROM Win32_DiskDrive
00002719 OK1:SELECT * FROM Win32_DiskDrive
00002797 while(pEnumCOMDevs ...
00002797 diskSize:256052966400
00002797 deviceId:\\.\PHYSICALDRIVE0
00002797 model:INTEL SSDPEKKW256G8
00002797 mediaType:Fixed hard disk media
00002797 interfaceTypeWmi:SCSI
00002797 pnpDeviceId:SCSI\DISK&VEN_NVME&PROD_INTEL_SSDPEKKW25\5&34F18CBF&1&000000
00002797 DO:GetDiskInfo pd=0, sp=0, st=0, mt=fixed hard disk media
00002797 INTERFACE_TYPE_NVME
00002797 flagTarget && GetDiskInfo
00002813 GetDiskInfo
00002813 DoIdentifyDeviceNVMeStorageQuery
00002813 AddDiskNVMe - CMD_TYPE_NVME_STORAGE_QUERY
00002891 index=2
00002891 index=2, previousCount=2
00002891 OK:Check Model Name
00002891 while(pEnumCOMDevs ...
00002891 diskSize:2000396321280
00002891 deviceId:\\.\PHYSICALDRIVE1
00002891 model:ST2000DM008-2FR102
00002891 mediaType:Fixed hard disk media
00002891 interfaceTypeWmi:IDE
00002891 pnpDeviceId:SCSI\DISK&VEN_ST2000DM&PROD_008-2FR102\4&20199404&0&000100
00002891 DO:GetDiskInfo pd=1, sp=1, st=1, mt=fixed hard disk media
00002891 flagTarget && GetDiskInfo
00002891 GetDiskInfo
00002907 DoIdentifyDevicePd(1, 0xA0) - 1
00002907 SendAtaCommandPd - IDENTIFY_DEVICE
00002907 AddDisk(1, 1, 1) - 6
00002907 vars[i].CommandType = CMD_TYPE_CSMI_PHYSICAL_DRIVE
00002907 GetSmartAttributePd(1) - 1
00002907 SendAtaCommandPd - SMART_READ_DATA
00002938 SendAtaCommandPd - SMART_READ_DATA
00002969 SendAtaCommandPd - SMART_READ_THRESHOLDS
00002985 index=2
00002985 while(pEnumCOMDevs ...
00002985 diskSize:4000784417280
00002985 deviceId:\\.\PHYSICALDRIVE2
00002985 model:ST4000NM000A-2HZ100
00002985 mediaType:Fixed hard disk media
00002985 interfaceTypeWmi:IDE
00002985 pnpDeviceId:SCSI\DISK&VEN_ST4000NM&PROD_000A-2HZ100\4&20199404&0&000400
00002985 DO:GetDiskInfo pd=2, sp=1, st=4, mt=fixed hard disk media
00002985 flagTarget && GetDiskInfo
00002985 GetDiskInfo
00002985 DoIdentifyDevicePd(2, 0xA0) - 1
00002985 SendAtaCommandPd - IDENTIFY_DEVICE
00002985 AddDisk(2, 1, 4) - 6
00002985 vars[i].CommandType = CMD_TYPE_CSMI_PHYSICAL_DRIVE
00002985 GetSmartAttributePd(2) - 1
00002985 SendAtaCommandPd - SMART_READ_DATA
00003000 SendAtaCommandPd - SMART_READ_DATA
00003000 SendAtaCommandPd - SMART_READ_THRESHOLDS
00003016 index=2
00003016 uReturned != 1
00003016 OK2:SELECT * FROM Win32_DiskDrive
00003016 OK:GetDiskInfo - PhysicalDrive
00003016 OK:qsort
00003016 Drive Letter Mapping - Start
00003016 A:\
00003016 Drive Letter Mapping - != DRIVE_FIXED
00003016 B:\
00003016 Drive Letter Mapping - != DRIVE_FIXED
00003016 C:\
00003016 \\.\C:
00003016 volumeDiskExtents.NumberOfDiskExtents = 1
00003016 n = 0, pDiskExtent->DiskNumber = 0
00003016 D:\
00003016 \\.\D:
00003016 volumeDiskExtents.NumberOfDiskExtents = 1
00003016 n = 0, pDiskExtent->DiskNumber = 1
00003016 E:\
00003016 Drive Letter Mapping - != DRIVE_FIXED
00003016 F:\
00003032 Drive Letter Mapping - != DRIVE_FIXED
00003032 G:\
00003032 Drive Letter Mapping - != DRIVE_FIXED
00003032 H:\
00003032 Drive Letter Mapping - != DRIVE_FIXED
00003032 I:\
00003032 Drive Letter Mapping - != DRIVE_FIXED
00003032 J:\
00003032 Drive Letter Mapping - != DRIVE_FIXED
00003032 K:\
00003032 Drive Letter Mapping - != DRIVE_FIXED
00003032 L:\
00003032 Drive Letter Mapping - != DRIVE_FIXED
00003032 M:\
00003032 \\.\M:
00003032 volumeDiskExtents.NumberOfDiskExtents = 1
00003032 n = 0, pDiskExtent->DiskNumber = 1
00003032 N:\
00003032 Drive Letter Mapping - != DRIVE_FIXED
00003032 O:\
00003032 Drive Letter Mapping - != DRIVE_FIXED
00003032 P:\
00003032 \\.\P:
00003047 volumeDiskExtents.NumberOfDiskExtents = 1
00003047 n = 0, pDiskExtent->DiskNumber = 1
00003047 Q:\
00003047 Drive Letter Mapping - != DRIVE_FIXED
00003047 R:\
00003047 Drive Letter Mapping - != DRIVE_FIXED
00003047 S:\
00003047 Drive Letter Mapping - != DRIVE_FIXED
00003047 T:\
00003047 Drive Letter Mapping - != DRIVE_FIXED
00003047 U:\
00003047 Drive Letter Mapping - != DRIVE_FIXED
00003047 V:\
00003047 Drive Letter Mapping - != DRIVE_FIXED
00003047 W:\
00003047 Drive Letter Mapping - != DRIVE_FIXED
00003047 X:\
00003047 Drive Letter Mapping - != DRIVE_FIXED
00003047 Y:\
00003047 Drive Letter Mapping - != DRIVE_FIXED
00003047 Z:\
00003047 Drive Letter Mapping - != DRIVE_FIXED
00003047 Drive Letter Mapping - End
00003047 C
00003063 D
00003063 M
00003063 P
00003063 CAtaSmart::Init - Complete
00003063 SaveSmartInfo(i)
00003391 SaveSmartInfo(i)
00003922 SaveSmartInfo(i)
00004313 CheckResident()
00004313 SetTimer(TIMER_SET_POWER_ON_UNIT, 130000, 0)
00004313 AutoAamApmAdaption()
00004313 UpdateShareInfo()
00004313 RegisterDeviceNotification
00004313 InitDialogComplete
00004313 RestorePos()
00004328 CheckStartup
00004328 CheckHideSerialNumber
00004328 ChangeZoomType
00004328 UpdateDialogSize
00004578 ChangeLang
00004641 CheckPage()
00004641 ShowWindow(SW_SHOW)

**Comment by hiyohiyo** [comment]
Thank you for log data.

Boot time is about 4.6 seconds. It may be normal.
I would like you to send the previous and fast boot version log.

**Comment by haobinnan** [comment]
00000000 8.13.0
00000031 2021/11/26
00000062 CreateMutex
00000078 AfxOleInit()
00000093 AfxOleGetMessageFilter()->SetMessagePendingDelay
00000109 AfxOleGetMessageFilter()->EnableNotRespondingDialog(FALSE)
00000125 AfxOleGetMessageFilter()->EnableBusyDialog(FALSE)
00000140 CDiskInfoDlg::CDiskInfoDlg - START
00000172 CDiskInfoDlg::CDiskInfoDlg - CENTER
00000187 CDiskInfoDlg::CDiskInfoDlg - END
00000218 dlg.DoModal()
00000265 InitAta
00000297 CAtaSmart::Init WMI on - Start
00000297 CoInitializeSecurity()
00000328 CoCreateInstance()
00000343 ConnectServer()
00000359 CoSetProxyBlanket()
00000375 OK:WMI Init
00001500 OK:Win32_IDEController
00001578 OK:Win32_SCSIController
00001593 --ControllerMap--
 - Microsoft 存储空间控制器 [SCSI]
 + Intel(R) Chipset SATA/PCIe RST Premium Controller [SCSI]
   - Intel Raid 0 Volume
   - 通用软件组件
 + Intel(R) SSD Pro 7600p/760p/E 6100p Series [SCSI]
   - INTEL SSDPEKKW256G8
 + 标准 NVM Express 控制器 [SCSI]
   - WDS100T3X0C-00SJG0

00001672 OK:Win32_USBController
00001687 WakeUp(0)
00001703 WakeUp(1)
00001718 WakeUp(2)
00001734 DoIdentifyDeviceCsmi
00001750 asi.Model.IsEmpty() || asi.FirmwareRev.IsEmpty()
00001765 DoIdentifyDeviceCsmi
00001781 asi.Model.IsEmpty() || asi.FirmwareRev.IsEmpty()
00001797 DoIdentifyDeviceCsmi
00001812 GetSmartAttributeCsmi
00001906 FillSmartData
00001922 GetSmartAttributeCsmi
00002015 FillSmartData
00002031 GetSmartThresholdCsmi
00002062 FillSmartThreshold
00002093 DoIdentifyDeviceCsmi
00002250 GetSmartAttributeCsmi
00002343 FillSmartData
00002375 GetSmartAttributeCsmi
00002468 FillSmartData
00002500 GetSmartThresholdCsmi
00002531 FillSmartThreshold
00002562 DO:SELECT * FROM Win32_DiskDrive
00002578 OK1:SELECT * FROM Win32_DiskDrive
00002593 while(pEnumCOMDevs ...
00002609 diskSize:4000784417280
00002625 deviceId:\\.\PHYSICALDRIVE2
00002640 model:Intel Raid 0 Volume
00002672 mediaType:Fixed hard disk media
00002703 interfaceTypeWmi:SCSI
00002718 pnpDeviceId:SCSI\DISK&VEN_INTEL&PROD_RAID_0_VOLUME\4&2CB270B9&0&060200
00002734 DO:GetDiskInfo pd=2, sp=2, st=2, mt=fixed hard disk media
00002750 flagTarget && GetDiskInfo
00002765 GetDiskInfo
00002781 DoIdentifyDevicePd(2, 0xA0) - 1
00002797 SendAtaCommandPd - IDENTIFY_DEVICE (ATA_PASS_THROUGH)
00002812 SendAtaCommandPd - IDENTIFY_DEVICE
00002843 AddDisk(2, 2, 2) - 6
00002859 while(pEnumCOMDevs ...
00002875 diskSize:256052966400
00002890 deviceId:\\.\PHYSICALDRIVE1
00002906 model:INTEL SSDPEKKW256G8
00002937 mediaType:Fixed hard disk media
00002953 interfaceTypeWmi:SCSI
00002984 pnpDeviceId:SCSI\DISK&VEN_NVME&PROD_INTEL_SSDPEKKW25\5&384CE965&0&000000
00003015 DO:GetDiskInfo pd=1, sp=1, st=0, mt=fixed hard disk media
00003047 INTERFACE_TYPE_NVME
00003062 flagTarget && GetDiskInfo
00003078 GetDiskInfo
00003109 DoIdentifyDeviceNVMeStorageQuery
00003125 AddDiskNVMe - CMD_TYPE_NVME_STORAGE_QUERY
00003234 index=2
00003234 index=2, previousCount=2
00003265 OK:Check Model Name
00003265 while(pEnumCOMDevs ...
00003312 diskSize:1000202273280
00003328 deviceId:\\.\PHYSICALDRIVE0
00003343 model:WDS100T3X0C-00SJG0
00003359 mediaType:Fixed hard disk media
00003375 interfaceTypeWmi:SCSI
00003390 pnpDeviceId:SCSI\DISK&VEN_NVME&PROD_WDS100T3X0C-00SJ\5&16BC72C4&0&000000
00003406 DO:GetDiskInfo pd=0, sp=0, st=0, mt=fixed hard disk media
00003422 INTERFACE_TYPE_NVME
00003468 flagTarget && GetDiskInfo
00003484 GetDiskInfo
00003500 DoIdentifyDeviceNVMeStorageQuery
00003515 AddDiskNVMe - CMD_TYPE_NVME_STORAGE_QUERY
00003609 index=3
00003625 index=3, previousCount=3
00003640 OK:Check Model Name
00003672 uReturned != 1
00003687 OK2:SELECT * FROM Win32_DiskDrive
00003718 USB-HDD Check
00003734 Check Bus Type
00003765 DO:GetDiskInfo
00003781 GetDiskInfo
00003797 DoIdentifyDevicePd(2, 0xA0) - 1
00003812 SendAtaCommandPd - IDENTIFY_DEVICE (ATA_PASS_THROUGH)
00003843 SendAtaCommandPd - IDENTIFY_DEVICE
00003859 AddDisk(2, -1, -1) - 6
00003890 OK:GetDiskInfo - PhysicalDrive
00003906 OK:qsort
00003937 Drive Letter Mapping - Start
00003968 A:\
00003984 Drive Letter Mapping - != DRIVE_FIXED
00004015 B:\
00004031 Drive Letter Mapping - != DRIVE_FIXED
00004047 C:\
00004062 \\.\C:
00004093 volumeDiskExtents.NumberOfDiskExtents = 1
00004109 n = 0, pDiskExtent->DiskNumber = 1
00004125 D:\
00004156 \\.\D:
00004172 volumeDiskExtents.NumberOfDiskExtents = 1
00004187 n = 0, pDiskExtent->DiskNumber = 0
00004218 E:\
00004250 \\.\E:
00004265 volumeDiskExtents.NumberOfDiskExtents = 1
00004297 n = 0, pDiskExtent->DiskNumber = 2
00004328 F:\
00004343 Drive Letter Mapping - != DRIVE_FIXED
00004375 G:\
00004390 Drive Letter Mapping - != DRIVE_FIXED
00004422 H:\
00004453 Drive Letter Mapping - != DRIVE_FIXED
00004468 I:\
00004500 Drive Letter Mapping - != DRIVE_FIXED
00004531 J:\
00004547 Drive Letter Mapping - != DRIVE_FIXED
00004578 K:\
00004593 Drive Letter Mapping - != DRIVE_FIXED
00004640 L:\
00004687 Drive Letter Mapping - != DRIVE_FIXED
00004703 M:\
00004734 Drive Letter Mapping - != DRIVE_FIXED
00004750 N:\
00004781 Drive Letter Mapping - != DRIVE_FIXED
00004797 O:\
00004812 Drive Letter Mapping - != DRIVE_FIXED
00004843 P:\
00004875 Drive Letter Mapping - != DRIVE_FIXED
00004890 Q:\
00004906 Drive Letter Mapping - != DRIVE_FIXED
00004922 R:\
00004937 Drive Letter Mapping - != DRIVE_FIXED
00004953 S:\
00004984 Drive Letter Mapping - != DRIVE_FIXED
00005015 T:\
00005031 Drive Letter Mapping - != DRIVE_FIXED
00005047 U:\
00005062 Drive Letter Mapping - != DRIVE_FIXED
00005093 V:\
00005109 Drive Letter Mapping - != DRIVE_FIXED
00005140 W:\
00005172 Drive Letter Mapping - != DRIVE_FIXED
00005187 X:\
00005218 Drive Letter Mapping - != DRIVE_FIXED
00005250 Y:\
00005265 Drive Letter Mapping - != DRIVE_FIXED
00005281 Z:\
00005312 Drive Letter Mapping - != DRIVE_FIXED
00005343 Drive Letter Mapping - End
00005375 D
00005390 C
00005422 CAtaSmart::Init - Complete
00005437 SaveSmartInfo(i)
00005468 SaveSmartInfo(i)
00005500 SaveSmartInfo(i)
00005531 SaveSmartInfo(i)
00005562 CheckResident()
00005593 SetTimer(TIMER_SET_POWER_ON_UNIT, 130000, 0)
00005609 AutoAamApmAdaption()
00005640 UpdateShareInfo()
00005656 RegisterDeviceNotification
00005687 InitDialogComplete
00005718 RestorePos()
00005750 CheckStartup
00005781 CheckHideSerialNumber
00005812 ChangeZoomType
00005828 UpdateDialogSize
00006031 ChangeLang
00006062 GetSmartAttributeCsmi
00006187 FillSmartData
00006265 CheckPage()
00006312 ShowWindow(SW_SHOW)

**Comment by haobinnan** [comment]
I'm sorry, I cannot find the fast booting version. It seems that it has something to do with the wd nvme disks. I can guarantee the wd nvme disk is normal. I hope the CAtaSmart class can be optimized so that the boot speed can be improved.

**Comment by hiyohiyo** [comment]
I would like to optimize CAtaSmart in the future release.
