### ISSUE TITLE
64 Disks Limit

### ISSUE THREAD

**Issue by MainMagicMan** [hiyohiyo/CrystalDiskInfo#156]
Thank you very much for the great App!

ISSUE:
Please remove the limit of 64 Disks or make it configurable in the App instead of using a fixed value.

SOLUTION (for me):
Made a Fork with Support for 128 Disks.
If anyone is interested, its here: https://github.com/MainMagicMan/CrystalDiskInfo/releases/tag/8.12.13.0-1

**Comment by hiyohiyo** [comment]
Thank you for your request.

I will add 128 drives support!!
https://crystalmark.info/download/zz/CrystalDiskInfo8_13_0Beta.zip

I would like you to send the result "File > Save (txt)".
And if you don't mind, I'd like to see a picture of your computer with many drives connected to it.

**Comment by hiyohiyo** [comment]
I released CrystalDiskInfo 8.13.0.
