### ISSUE TITLE
Advanced format 4Kn sector device identification is incorrect

### ISSUE THREAD

**Issue by nasbdh9** [hiyohiyo/CrystalDiskInfo#16]
![avatar](https://i.loli.net/2018/09/10/5b9668fe27f07.png)
This is a 4Kn sector device but the capacity identification is not correct, maybe this is because of windows api problem?

Is it possible to record all Smart? Currently, recording only the current value may be inaccurate for judging certain hard drives.

**Comment by nasbdh9** [comment]
long time ago, I realized that this may be a Windows API problem. Under the native 4Kn format hard drive, the correct capacity should be eight times the displayed value

**Comment by kravena** [comment]
I am experiencing this same issue after changing from 512e to 4kn

**Comment by hiyohiyo** [comment]
@kravena I would like you to send text copy to me. hiyohiyo@crystalmark.info or this thread. I will support near future.

**Comment by kravena** [comment]
I can't give you full info, as I have the drives raided, but I have provided what I can below :

However, these are 14TB WD Drives WD140EMFZ which I have reformatted from 512e to 4kn using the WD Hugo tool. I also did the same with the 12TB WD Gold drives I have WD121KRYZ which has the same issue in Diskinfo.

[
[drive.txt](https://github.com/hiyohiyo/CrystalDiskInfo/files/4965189/drive.txt)
](url)

[diskinfo.txt](https://github.com/hiyohiyo/CrystalDiskInfo/files/4965214/diskinfo.txt)
![megaraid](https://user-images.githubusercontent.com/16151488/88275759-d01ec800-ccd5-11ea-8d30-22bb057b2f9b.png)

Hugo command used : 
 f -m <DRIVE MODEL> --fastformat -b 4096

**Comment by hiyohiyo** [comment]
Thank you detail information. I will support 4Kn future release!!

**Comment by hiyohiyo** [comment]
CrystalDiskInfo 8.8.0 Alpha1 or later supports 4Kn. Please test it.
https://crystalmark.info/en/

**Comment by nasbdh9** [comment]
![QQ截图20200724102433](https://user-images.githubusercontent.com/26650222/88355655-f7d66480-cd97-11ea-8b28-7f4f3fe46835.png)

Tested in 8.8.0 Alpha1, shows the correct capacity👍

**Comment by kravena** [comment]
Yes, it works

**Comment by hiyohiyo** [comment]
CrystalDiskInfo 8.8 will be released near future.
