### ISSUE TITLE
Kingston SSD can return Caution (Available Spare)

### ISSUE THREAD

**Issue by SkyEmie** [hiyohiyo/CrystalDiskInfo#161]
Hi,

I noticed that some kingston ssd can display "Caution", while on the older versions it was not the case.
Version 8.13.0 :
![image](https://user-images.githubusercontent.com/29162548/145678398-0ac76595-8946-44e6-8509-224083db163d.png)

And this:
[output.log](https://github.com/hiyohiyo/CrystalDiskInfo/files/7697105/output.log)

It looks like a problem with the "Available Spare"?
Value and the threshold seem to be identical. In others softwares, the value is 100.

Hope this will help you!
Emie

**Comment by hiyohiyo** [comment]
Thank you for your report.
I will fix this problem in the next release.

**Comment by hiyohiyo** [comment]
I will fix it. Please test version.
https://crystalmark.info/download/zz/CrystalDiskInfo8_13_1.zip

**Comment by SkyEmie** [comment]
That sounds good I guess!
What was the origin of the problem?

Emie

[logs.txt](https://github.com/hiyohiyo/CrystalDiskInfo/files/7714263/logs.txt)

![image](https://user-images.githubusercontent.com/29162548/146067383-4855595f-ec5d-4b40-ab33-1ef82238708f.png)

**Comment by hiyohiyo** [comment]
Thank you for testing. I will release CrystalDiskInfo 8.3.1 ASAP.

<img width="663" alt="image" src="https://user-images.githubusercontent.com/3816714/146094655-310c6001-b1b1-4325-8e1e-646cc2e1b55b.png">
