### ISSUE TITLE
Wrong Attribute Name for OCZ Vertex Turbo

### ISSUE THREAD

**Issue by VerTigoNTxvii** [hiyohiyo/CrystalDiskInfo#166]
Since version 8.12.xx of CDI the Attribute Name lost, just Vendor Specific, but raw Values is right

----------------------------------------------------------------------------
 (07) OCZ VERTEX-TURBO
----------------------------------------------------------------------------
           Model : OCZ VERTEX-TURBO
        Firmware : 1.7
   Serial Number : 03258UK26TN0391IZO87
       Disk Size : 32,0 GB (8,4/32,0/32,0/32,0)
     Buffer Size : >= 32767 KB
     Queue Depth : 32
    # of Sectors : 62533296
   Rotation Rate : ---- (SSD)
       Interface : Serial ATA
   Major Version : ATA8-ACS
   Minor Version : ----
   Transfer Mode : ---- | SATA/300
  Power On Hours : 51369 ч
  Power On Count : 2288 раз
     Temperature : Неизвестно
   Health Status : Хорошо (100 %)
        Features : S.M.A.R.T., NCQ, TRIM
       APM Level : ----
       AAM Level : ----
    Drive Letter : C:

-- S.M.A.R.T. --------------------------------------------------------------
ID Raw Values (8)   Attribute Name
01 0000000000000007 Vendor Specific
09 000000000000C8A9 Vendor Specific
0C 00000000000008F0 Vendor Specific
B8 0000000000000002 Vendor Specific
C3 0000000000000000 Vendor Specific
C4 0000000000000000 Vendor Specific
C5 0000000000000000 Vendor Specific
C6 00000002E79FE332 Vendor Specific
C7 0000000275243A9A Vendor Specific
C8 0000000008E481FA Vendor Specific
C9 000000001019404D Vendor Specific
CA 00000000004349FB Vendor Specific
CB 00000000003FB463 Vendor Specific
CC 0000000000000000 Vendor Specific
CD 0000000000001388 Vendor Specific
CE 0000000000001B28 Vendor Specific
CF 0000000000002E63 Vendor Specific
D0 00000000000021D2 Vendor Specific
D1 0000000000000064 Vendor Specific
D3 0000000000000000 Vendor Specific
D4 0000000000000000 Vendor Specific
D5 0000000000000000 Vendor Specific

-- IDENTIFY_DEVICE ---------------------------------------------------------
        0    1    2    3    4    5    6    7    8    9
000: 0C5A 3FFF C837 0010 0000 0000 003F 0000 0000 0000
010: 3033 3235 3855 4B32 3654 4E30 3339 3149 5A4F 3837
020: 0000 FFFF 3000 312E 3720 2020 2020 4F43 5A20 5645
030: 5254 4558 2D54 5552 424F 2020 2020 2020 2020 2020
040: 2020 2020 2020 2020 2020 2020 2020 8001 0000 2F00
050: 4000 0200 0200 0007 3FFF 0010 003F FC10 00FB 0101
060: 2EB0 03BA 0000 0007 0003 0078 0078 0078 0078 0000
070: 0000 0000 0000 0000 0000 001F 0506 0000 0044 0044
080: 01E0 0000 346B 7D01 4022 3469 3C01 4022 407F 0000
090: 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
100: 2EB0 03BA 0000 0000 0000 0000 4000 0000 0000 0000
110: 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
120: 0000 0000 0000 0000 0000 0000 0000 0000 0009 0000
130: 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
140: 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
150: 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
160: 0000 0000 0000 0000 0000 0000 0000 0000 0000 0001
170: 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
180: 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
190: 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
200: 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
210: 0000 0000 0000 0000 0000 0000 0000 0001 0000 0000
220: 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
230: 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
240: 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
250: 0000 0000 0000 0000 0000 7FA5

-- SMART_READ_DATA ---------------------------------------------------------
     +0 +1 +2 +3 +4 +5 +6 +7 +8 +9 +A +B +C +D +E +F
000: 10 00 01 00 00 07 00 00 00 00 00 00 00 00 09 00
010: 00 A9 C8 00 00 00 00 00 00 00 0C 00 00 F0 08 00
020: 00 00 00 00 00 00 B8 00 00 02 00 00 00 00 00 00
030: 00 00 C3 00 00 00 00 00 00 00 00 00 00 00 C4 00
040: 00 00 00 00 00 00 00 00 00 00 C5 00 00 00 00 00
050: 00 00 00 00 00 00 C6 00 00 32 E3 9F E7 02 00 00
060: 00 00 C7 00 00 9A 3A 24 75 02 00 00 00 00 C8 00
070: 00 FA 81 E4 08 00 00 00 00 00 C9 00 00 4D 40 19
080: 10 00 00 00 00 00 CA 00 00 FB 49 43 00 00 00 00
090: 00 00 CB 00 00 63 B4 3F 00 00 00 00 00 00 CC 00
0A0: 00 00 00 00 00 00 00 00 00 00 CD 00 00 88 13 00
0B0: 00 00 00 00 00 00 CE 00 00 28 1B 00 00 00 00 00
0C0: 00 00 CF 00 00 63 2E 00 00 00 00 00 00 00 D0 00
0D0: 00 D2 21 00 00 00 00 00 00 00 D1 00 00 64 00 00
0E0: 00 00 00 00 00 00 D3 00 00 00 00 00 00 00 00 00
0F0: 00 00 D4 00 00 00 00 00 00 00 00 00 00 00 D5 00
100: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
110: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
120: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
130: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
140: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
150: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
160: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 1D
170: 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
180: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
190: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1A0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1B0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1C0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1D0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1E0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1F0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 72

-- SMART_READ_THRESHOLD ----------------------------------------------------
     +0 +1 +2 +3 +4 +5 +6 +7 +8 +9 +A +B +C +D +E +F
000: 10 00 01 00 00 07 00 00 00 00 00 00 00 00 09 00
010: 00 A8 C8 00 00 00 00 00 00 00 0C 00 00 F0 08 00
020: 00 00 00 00 00 00 B8 00 00 02 00 00 00 00 00 00
030: 00 00 C3 00 00 00 00 00 00 00 00 00 00 00 C4 00
040: 00 00 00 00 00 00 00 00 00 00 C5 00 00 00 00 00
050: 00 00 00 00 00 00 C6 00 00 6B C5 9F E7 02 00 00
060: 00 00 C7 00 00 2F DC 21 75 02 00 00 00 00 C8 00
070: 00 74 81 E4 08 00 00 00 00 00 C9 00 00 06 15 19
080: 10 00 00 00 00 00 CA 00 00 F9 49 43 00 00 00 00
090: 00 00 CB 00 00 61 B4 3F 00 00 00 00 00 00 CC 00
0A0: 00 00 00 00 00 00 00 00 00 00 CD 00 00 88 13 00
0B0: 00 00 00 00 00 00 CE 00 00 28 1B 00 00 00 00 00
0C0: 00 00 CF 00 00 63 2E 00 00 00 00 00 00 00 D0 00
0D0: 00 D2 21 00 00 00 00 00 00 00 D1 00 00 64 00 00
0E0: 00 00 00 00 00 00 D3 00 00 00 00 00 00 00 00 00
0F0: 00 00 D4 00 00 00 00 00 00 00 00 00 00 00 D5 00
100: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
110: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
120: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
130: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
140: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
150: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
160: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 1D
170: 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
180: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
190: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1A0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1B0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1C0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1D0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1E0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1F0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 20

**Comment by hiyohiyo** [comment]
Hi,
Please send the complete log (File > Save(Text)) and "DiskInfo.log" to hiyohiyo@crystalmark.info.

## How to output “DiskInfo.log”
Default setting of CrystalDiskInfo does not output DiskInfo.log, so please edit DiskInfo.ini to change Debug Mode.

[Setting]
DebugMode=0 ：No Debug log (DiskInfo.log) *default
DebugMode=1 ：Debug log (DiskInfo.log)
DebugMode=2 ：Debug log and message

https://crystalmark.info/en/software/crystaldiskinfo/crystaldiskinfo-contact/

**Comment by VerTigoNTxvii** [comment]
Thank you for quick response & help!!!
