### ISSUE TITLE
Kingston SUV400S37240G

### ISSUE THREAD

**Issue by torpfwp** [hiyohiyo/CrystalDiskInfo#17]
Most of the items are displayed as "Vendor Specific".
The S.M.A.R.T. information of this model can be obtained from the following software.

Kingston SSD Toolbox
https://www.hyperxgaming.com/jp/support/technical/kingston-ssd-toolbox

Exported Data
[suv400s37240g.txt](https://github.com/hiyohiyo/CrystalDiskInfo/files/2608251/suv400s37240g.txt)

**Comment by hiyohiyo** [comment]
Improved Kingston SATA SSD support by CrystalDiskInfo 8.8.0 Alpha3
