### ISSUE TITLE
Use 'AtaSmart' library on another function

### ISSUE THREAD

**Issue by camambeou** [hiyohiyo/CrystalDiskInfo#177]
I try to mod this project to separate services and UI ([issue 60])(https://github.com/hiyohiyo/CrystalDiskInfo/issues/60)
I write a .cpp to use 'AtaSmart' library like this:

`CAtaSmart m_Ata{};`
`m_Ata.Init(1, 1, 0, 1, 1, 1);`
`ofstream myFile("C:\\ModelSerial.txt");`
`myFile << CT2A(m_Ata.vars[0].ModelSerial);`
` myFile.close();`

ModelSerials of SATA disks are got.
But ModelSerials of NVMe disk is always null. Seem not found these disks.
How can I fix that? Or where am I wrong?

**Comment by camambeou** [comment]
`CArray<ATA_SMART_INFO, ATA_SMART_INFO> vars` is always empty in this situation.

**Comment by camambeou** [comment]
I guess thì code cause that:
`if (IsWindowsVersionOrGreaterFx(10, 0))
	{
		m_bAtaPassThrough = TRUE;
		m_bAtaPassThroughSmart = TRUE;
		m_bNVMeStorageQuery = TRUE;
	}
	else if (IsWindowsVersionOrGreaterFx(6, 0) || IsWindowsVersionOrGreaterFx(5, 2))
	{
		m_bAtaPassThrough = TRUE;
		m_bAtaPassThroughSmart = TRUE;
	}
	else if (IsWindowsVersionOrGreaterFx(5, 1))
	{
		if (IsWindowsVersionOrGreaterFx(5, 1, 2))
		{
			m_bAtaPassThrough = TRUE;
			m_bAtaPassThroughSmart = TRUE;
		}
	}`
Run on Windows 10, the above code leads to `else if (IsWindowsVersionOrGreaterFx(6, 0) || IsWindowsVersionOrGreaterFx(5, 2))`

**Comment by camambeou** [comment]
I found my issue

**Comment by zyyujq** [comment]
How to solve the problem? How to modify the code?

**Comment by zyyujq** [comment]
It seems to be related to the operating system, WIN11 error, WIN7 can!

**Comment by zyyujq** [comment]
#include<iostream> 
#include<fstream>
using namespace std;

CAtaSmart m_Ata{};
m_Ata.Init(1, 1, 0, 1, 1, 1);
ofstream myFile("C:\\ModelSerial.txt");
myFile << CT2A(m_Ata.vars[0].ModelSerial);
 myFile.close();


WIN7 passed!
