### ISSUE TITLE
Kingston SSD health on certain Firmware.

### ISSUE THREAD

**Issue by wecome42** [hiyohiyo/CrystalDiskInfo#178]
Hello, I am using a Kingston SSD as my OS drive and I use CrystalDiskInfo all the time to check the health of the drives. However the drive shows Unknown 87%. According to the Kingston SSD Manager it shows 87% life so this is correct. I have updated the firmware and seems to be the same.

Firmware: SBFKB1H5
Model: KINGSTON SA400S37120G

![image](https://user-images.githubusercontent.com/81438361/176682315-4657f283-385d-4182-bcbb-b8b965568530.png)

**Comment by hiyohiyo** [comment]
Please attach the text copy (Edit > Copy) and DiskInfo.log.
https://crystalmark.info/en/software/crystaldiskinfo/crystaldiskinfo-contact/

**Comment by wecome42** [comment]
----------------------------------------------------------------------------
CrystalDiskInfo 8.17.3 (C) 2008-2022 hiyohiyo
                                Crystal Dew World: https://crystalmark.info/
----------------------------------------------------------------------------

    OS : Windows 10 Professional [10.0 Build 19043] (x64)
  Date : 2022/07/01 17:51:53

-- Controller Map ----------------------------------------------------------
 + Standard SATA AHCI Controller [ATA]
   - SAMSUNG HD321KJ
   - KINGSTON SA400S37120G
 - Microsoft Storage Spaces Controller [SCSI]

-- Disk List ---------------------------------------------------------------
 (01) SAMSUNG HD321KJ : 320.0 GB [0/0/0, pd1]
 (02) KINGSTON SA400S37120G : 120.0 GB [1/0/0, pd1] - ki

----------------------------------------------------------------------------
 (01) SAMSUNG HD321KJ
----------------------------------------------------------------------------
           Model : SAMSUNG HD321KJ
        Firmware : CP100-10
   Serial Number : *****************
       Disk Size : 320.0 GB (8.4/137.4/320.0/320.0)
     Buffer Size : 16384 KB
     Queue Depth : 32
    # of Sectors : 625142448
   Rotation Rate : Unknown
       Interface : Serial ATA
   Major Version : ATA8-ACS
   Minor Version : ATA8-ACS version 3b
   Transfer Mode : ---- | SATA/300
  Power On Hours : 7028 hours
  Power On Count : 592 count
     Temperature : 27 C (80 F)
   Health Status : Good
        Features : S.M.A.R.T., AAM, NCQ
       APM Level : ----
       AAM Level : FE00h [OFF]
    Drive Letter : E:

-- S.M.A.R.T. --------------------------------------------------------------
ID Cur Wor Thr RawValues(6) Attribute Name
01 100 100 _51 000000000000 Read Error Rate
03 100 100 _15 0000000015C0 Spin-Up Time
04 100 100 __0 000000000384 Start/Stop Count
05 253 253 _10 000000000000 Reallocated Sectors Count
07 253 253 _51 000000000000 Seek Error Rate
08 253 253 _15 000000000000 Seek Time Performance
09 100 100 __0 000000001B74 Power-On Hours
0A 253 253 _51 000000000000 Spin Retry Count
0B 253 100 __0 000000000000 Recalibration Retries
0C 100 100 __0 000000000250 Power Cycle Count
BB 253 253 __0 000000000000 Reported Uncorrectable Errors
BC 253 253 __0 000000000000 Command Timeout
BE _73 _53 __0 00000000001B Airflow Temperature
C2 157 _97 __0 00000000001B Temperature
C3 100 100 __0 0000001150C9 Hardware ECC recovered
C4 253 253 __0 000000000000 Reallocation Event Count
C5 253 253 __0 000000000000 Current Pending Sector Count
C6 253 253 __0 000000000000 Uncorrectable Sector Count
C7 200 200 __0 000000000000 UltraDMA CRC Error Count
C8 100 100 __0 000000000000 Write Error Rate
C9 253 100 __0 000000000000 Soft Read Error Rate
CA 253 253 __0 000000000000 Data Address Mark Error

-- IDENTIFY_DEVICE ---------------------------------------------------------
        0    1    2    3    4    5    6    7    8    9
000: 0040 3FFF C837 0010 8856 022A 003F 0000 0000 0000
010: 5330 4D51 4A31 5150 3531 3039 3532 2020 2020 2020
020: 0003 8000 0004 4350 3130 302D 3130 5341 4D53 554E
030: 4720 4844 3332 314B 4A20 2020 2020 2020 2020 2020
040: 2020 2020 2020 2020 2020 2020 2020 8010 0000 2F00
050: 4000 0200 0200 0007 3FFF 0010 003F FC10 00FB 0110
060: FFFF 0FFF 0000 0007 0003 0078 0078 0078 0078 0000
070: 0000 0000 0000 0000 0000 001F 0706 0000 004C 0040
080: 01F8 0052 746B 7F01 4123 7469 BC01 4123 40FF 0038
090: 0038 0000 FFFE 0000 FE00 0000 0000 0000 0000 0000
100: EAB0 2542 0000 0000 0000 0000 0000 0000 5000 0F00
110: 1B51 0952 0000 0000 0000 0000 0000 0000 0000 4010
120: 4010 0000 0000 0000 0000 0000 0000 0000 0029 0000
130: 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
140: FFFF 0400 0E00 0003 0000 9A00 0300 2400 6420 3431
150: 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
160: 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
170: 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
180: 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
190: 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
200: 0000 0000 0000 0000 0000 0000 003F 0000 0000 0000
210: 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
220: 0000 0000 100F 0000 0000 0000 0000 0000 0000 0000
230: 0000 0000 0000 0000 0001 0400 0000 0000 0000 0000
240: 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
250: 0000 0000 0000 0000 0000 E1A5

-- SMART_READ_DATA ---------------------------------------------------------
     +0 +1 +2 +3 +4 +5 +6 +7 +8 +9 +A +B +C +D +E +F
000: 10 00 01 0F 00 64 64 00 00 00 00 00 00 00 03 07
010: 00 64 64 C0 15 00 00 00 00 00 04 32 00 64 64 84
020: 03 00 00 00 00 00 05 33 00 FD FD 00 00 00 00 00
030: 00 00 07 0F 00 FD FD 00 00 00 00 00 00 00 08 25
040: 00 FD FD 00 00 00 00 00 00 00 09 32 00 64 64 74
050: 1B 00 00 00 00 00 0A 33 00 FD FD 00 00 00 00 00
060: 00 00 0B 12 00 FD 64 00 00 00 00 00 00 00 0C 32
070: 00 64 64 50 02 00 00 00 00 00 BB 32 00 FD FD 00
080: 00 00 00 00 00 00 BC 32 00 FD FD 00 00 00 00 00
090: 00 00 BE 22 00 49 35 1B 00 00 00 00 00 00 C2 22
0A0: 00 9D 61 1B 00 00 00 00 00 00 C3 1A 00 64 64 C9
0B0: 50 11 00 00 00 00 C4 32 00 FD FD 00 00 00 00 00
0C0: 00 00 C5 12 00 FD FD 00 00 00 00 00 00 00 C6 30
0D0: 00 FD FD 00 00 00 00 00 00 00 C7 3E 00 C8 C8 00
0E0: 00 00 00 00 00 00 C8 0A 00 64 64 00 00 00 00 00
0F0: 00 00 C9 0A 00 FD 64 00 00 00 00 00 00 00 CA 32
100: 00 FD FD 00 00 00 00 00 00 00 00 00 00 00 00 00
110: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
120: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
130: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
140: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
150: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
160: 00 00 00 00 00 00 00 00 00 00 00 00 CF 16 00 5B
170: 03 00 01 00 02 64 00 00 00 00 00 00 00 00 00 00
180: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
190: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1A0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1B0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1C0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1D0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1E0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1F0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 1C

-- SMART_READ_THRESHOLD ----------------------------------------------------
     +0 +1 +2 +3 +4 +5 +6 +7 +8 +9 +A +B +C +D +E +F
000: 10 00 01 33 00 00 00 00 00 00 00 00 00 00 03 0F
010: 00 00 00 00 00 00 00 00 00 00 04 00 00 00 00 00
020: 00 00 00 00 00 00 05 0A 00 00 00 00 00 00 00 00
030: 00 00 07 33 00 00 00 00 00 00 00 00 00 00 08 0F
040: 00 00 00 00 00 00 00 00 00 00 09 00 00 00 00 00
050: 00 00 00 00 00 00 0A 33 00 00 00 00 00 00 00 00
060: 00 00 0B 00 00 00 00 00 00 00 00 00 00 00 0C 00
070: 00 00 00 00 00 00 00 00 00 00 BB 00 00 00 00 00
080: 00 00 00 00 00 00 BC 00 00 00 00 00 00 00 00 00
090: 00 00 BE 00 00 00 00 00 00 00 00 00 00 00 C2 00
0A0: 00 00 00 00 00 00 00 00 00 00 C3 00 00 00 00 00
0B0: 00 00 00 00 00 00 C4 00 00 00 00 00 00 00 00 00
0C0: 00 00 C5 00 00 00 00 00 00 00 00 00 00 00 C6 00
0D0: 00 00 00 00 00 00 00 00 00 00 C7 00 00 00 00 00
0E0: 00 00 00 00 00 00 C8 00 00 00 00 00 00 00 00 00
0F0: 00 00 C9 00 00 00 00 00 00 00 00 00 00 00 CA 00
100: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
110: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
120: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
130: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
140: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
150: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
160: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
170: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
180: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
190: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1A0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1B0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1C0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1D0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1E0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1F0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 BE

----------------------------------------------------------------------------
 (02) KINGSTON SA400S37120G
----------------------------------------------------------------------------
           Model : KINGSTON SA400S37120G
        Firmware : SBFKB1H5
   Serial Number : *****************
       Disk Size : 120.0 GB (8.4/120.0/120.0/120.0)
     Buffer Size : Unknown
     Queue Depth : 32
    # of Sectors : 234441648
   Rotation Rate : ---- (SSD)
       Interface : Serial ATA
   Major Version : ACS-3
   Minor Version : ACS-3 Revision 4
   Transfer Mode : SATA/600 | SATA/600
  Power On Hours : 4089 hours
  Power On Count : 802 count
      Host Reads : 5437 GB
     Host Writes : 5597 GB
     NAND Writes : 9758 GB
     Temperature : 30 C (86 F)
   Health Status : Unknown (86 %)
        Features : S.M.A.R.T., APM, NCQ, TRIM
       APM Level : 0000h [OFF]
       AAM Level : ----
    Drive Letter : C:

-- S.M.A.R.T. --------------------------------------------------------------
ID Cur Wor Thr RawValues(6) Attribute Name
01 __0 100 __0 000000000000 Uncorrectable Errors
09 100 100 __0 000000000FF9 Power On Hours
0C 100 100 __0 000000000322 Power Cycles
94 100 100 __0 000000000000 Vendor Unique
95 100 100 __0 000000000000 Vendor Unique
A7 100 100 __0 000000000000 Vendor Unique
A8 100 100 __0 000000000000 SATA PHY Error Count
A9 100 100 __0 00000000000A Vendor Unique
AA 100 100 __0 000000000007 Bad Block Count
AC 100 100 __0 000000000000 Vendor Unique
AD 100 100 __0 000000830096 Erase Count
B5 100 100 __0 000000000000 Vendor Unique
B6 100 100 __0 000000000000 Vendor Unique
BB 100 100 __0 000000000000 Uncorrectable ECC Errors
C0 100 100 __0 000000000031 Vendor Specific
C2 _70 _62 __0 000C0026001E Temperature
C4 100 100 __0 000000000000 Reallocation Events
C7 100 100 __0 000000000000 SATA CRC Error
DA 100 100 __0 000000000000 CRC Error Count
E7 _14 _14 __0 000000000056 SSD Wear Indicator
E9 100 100 __0 00000000261E Lifetime Nand Writes
F1 100 100 __0 0000000015DD Lifetime Writes from Host
F2 100 100 __0 00000000153D Lifetime Read from Host
F4 100 100 __0 000000000083 Average Erase Count
F5 100 100 __0 000000000096 Max Erase Count
F6 100 100 __0 00000007C1C8 Total Erase Count
F6 100 100 __0 00000007C1C8 Total Erase Count

-- IDENTIFY_DEVICE ---------------------------------------------------------
        0    1    2    3    4    5    6    7    8    9
000: 0040 3FFF C837 0010 0000 0000 003F 0000 0000 0000
010: 3530 3032 3642 3736 3832 3631 4636 4642 2020 2020
020: 0000 0000 0000 5342 464B 4231 4835 4B49 4E47 5354
030: 4F4E 2053 4134 3030 5333 3731 3230 4720 2020 2020
040: 2020 2020 2020 2020 2020 2020 2020 8001 4000 2F00
050: 4000 0000 0000 0007 3FFF 0010 003F FC10 00FB 0101
060: 4BB0 0DF9 0000 0007 0003 0078 0078 0078 0078 0C00
070: 0000 0000 0000 0000 0000 001F 850E 0006 004C 0040
080: 07F8 011B 746B 7409 4160 7469 B401 4160 407F 000A
090: 001E 0000 FFFE 0000 0000 0000 0000 0000 0000 0000
100: 4BB0 0DF9 0000 0000 0000 0008 4000 0000 5002 6B76
110: 8261 F6FB 0000 0000 0000 0000 0000 0000 0000 401C
120: 401C 0000 0000 0000 0000 0000 0000 0000 0029 0000
130: 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
140: 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
150: 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
160: 0000 0000 0000 0000 0000 0000 0000 0000 0000 0001
170: 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
180: 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
190: 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
200: 0000 0000 0000 0000 0000 0000 0000 0000 0000 4000
210: 0000 0000 0000 0000 0000 0000 0000 0001 0000 0000
220: 0000 0000 10FF 0000 0000 0000 0000 0000 0000 0000
230: 0000 0000 0000 0000 0001 0400 0000 0000 0000 0000
240: 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
250: 0000 0000 0000 0000 0000 0EA5

-- SMART_READ_DATA ---------------------------------------------------------
     +0 +1 +2 +3 +4 +5 +6 +7 +8 +9 +A +B +C +D +E +F
000: 10 00 01 32 00 00 64 00 00 00 00 00 00 00 09 32
010: 00 64 64 F9 0F 00 00 00 00 00 0C 32 00 64 64 22
020: 03 00 00 00 00 00 94 00 00 64 64 00 00 00 00 00
030: 00 00 95 00 00 64 64 00 00 00 00 00 00 00 A7 00
040: 00 64 64 00 00 00 00 00 00 00 A8 12 00 64 64 00
050: 00 00 00 00 00 00 A9 00 00 64 64 0A 00 00 00 00
060: 00 00 AA 00 00 64 64 07 00 00 00 00 00 00 AC 32
070: 00 64 64 00 00 00 00 00 00 00 AD 00 00 64 64 96
080: 00 83 00 00 00 00 B5 32 00 64 64 00 00 00 00 00
090: 00 00 B6 00 00 64 64 00 00 00 00 00 00 00 BB 32
0A0: 00 64 64 00 00 00 00 00 00 00 C0 12 00 64 64 31
0B0: 00 00 00 00 00 00 C2 22 00 46 3E 1E 00 26 00 0C
0C0: 00 00 C4 32 00 64 64 00 00 00 00 00 00 00 C7 32
0D0: 00 64 64 00 00 00 00 00 00 00 DA 32 00 64 64 00
0E0: 00 00 00 00 00 00 E7 00 00 0E 0E 56 00 00 00 00
0F0: 00 00 E9 32 00 64 64 1E 26 00 00 00 00 00 F1 32
100: 00 64 64 DD 15 00 00 00 00 00 F2 32 00 64 64 3D
110: 15 00 00 00 00 00 F4 00 00 64 64 83 00 00 00 00
120: 00 00 F5 00 00 64 64 96 00 00 00 00 00 00 F6 00
130: 00 64 64 C8 C1 07 00 00 00 00 F6 00 00 64 64 C8
140: C1 07 00 00 00 00 00 00 00 00 00 00 00 00 00 00
150: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
160: 00 00 00 00 00 00 00 00 00 00 00 00 FF FF 00 11
170: 03 00 01 00 01 02 00 02 00 00 00 00 00 00 00 00
180: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
190: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1A0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1B0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1C0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1D0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1E0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1F0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 B8

-- SMART_READ_THRESHOLD ----------------------------------------------------
     +0 +1 +2 +3 +4 +5 +6 +7 +8 +9 +A +B +C +D +E +F
000: 10 00 01 00 00 00 00 00 00 00 00 00 00 00 09 00
010: 00 00 00 00 00 00 00 00 00 00 0C 00 00 00 00 00
020: 00 00 00 00 00 00 94 00 00 00 00 00 00 00 00 00
030: 00 00 95 00 00 00 00 00 00 00 00 00 00 00 A7 00
040: 00 00 00 00 00 00 00 00 00 00 A8 00 00 00 00 00
050: 00 00 00 00 00 00 A9 00 00 00 00 00 00 00 00 00
060: 00 00 AA 00 00 00 00 00 00 00 00 00 00 00 AC 00
070: 00 00 00 00 00 00 00 00 00 00 AD 00 00 00 00 00
080: 00 00 00 00 00 00 B5 00 00 00 00 00 00 00 00 00
090: 00 00 B6 00 00 00 00 00 00 00 00 00 00 00 BB 00
0A0: 00 00 00 00 00 00 00 00 00 00 C0 00 00 00 00 00
0B0: 00 00 00 00 00 00 C2 00 00 00 00 00 00 00 00 00
0C0: 00 00 C4 00 00 00 00 00 00 00 00 00 00 00 C7 00
0D0: 00 00 00 00 00 00 00 00 00 00 DA 00 00 00 00 00
0E0: 00 00 00 00 00 00 E7 00 00 00 00 00 00 00 00 00
0F0: 00 00 E9 00 00 00 00 00 00 00 00 00 00 00 F1 00
100: 00 00 00 00 00 00 00 00 00 00 F2 00 00 00 00 00
110: 00 00 00 00 00 00 F4 00 00 00 00 00 00 00 00 00
120: 00 00 F5 00 00 00 00 00 00 00 00 00 00 00 F6 00
130: 00 00 00 00 00 00 00 00 00 00 F6 00 00 00 00 00
140: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
150: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
160: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
170: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
180: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
190: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1A0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1B0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1C0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1D0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1E0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1F0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 21

**Comment by hiyohiyo** [comment]
Sorry, too late reply.
Thank you for log data.

All threshold data is 0. So, CrystalDiskInfo reports Unknown as health status.

F6 attribute is duplicated. It may buggy firmware...

F6 100 100 __0 00000007C1C8 Total Erase Count
F6 100 100 __0 00000007C1C8 Total Erase Count
