### ISSUE TITLE
intel s3500 (ver DELL EMC OEM) support?

### ISSUE THREAD

**Issue by kumoilain** [hiyohiyo/CrystalDiskInfo#18]
Will you support this SSD in future? Or can SMART information be modified by users?
Thanks!
![scs1](https://user-images.githubusercontent.com/29969516/50647255-1527c000-0fb3-11e9-9bf4-dbdb937f57d4.png)
![scs2](https://user-images.githubusercontent.com/29969516/50647265-1c4ece00-0fb3-11e9-91fa-f07644ebedbc.png)
Port SMART info from intel ssd toolbox:
[s3500.txt](https://github.com/hiyohiyo/CrystalDiskInfo/files/2724398/s3500.txt)

**Comment by kumoilain** [comment]
![1](https://user-images.githubusercontent.com/29969516/52272071-91317100-2980-11e9-983c-56fccb305fb4.png)
![2](https://user-images.githubusercontent.com/29969516/52272072-91ca0780-2980-11e9-8ff6-f0e2274f9fec.png)
![3](https://user-images.githubusercontent.com/29969516/52272076-9393cb00-2980-11e9-9b5c-6d20b97c4db7.png)
![4](https://user-images.githubusercontent.com/29969516/52272078-942c6180-2980-11e9-8084-ae044ee2b5a4.png)
These screenshots are taken from Intel SSD Toolbox. Thanks for your work.

**Comment by hiyohiyo** [comment]
CrystalDiskInfo 8.8.0 Alpha7
- Added Intel SSD DC 3500 Series
