### ISSUE TITLE
Error: Disk not found

### ISSUE THREAD

**Issue by luimen6** [hiyohiyo/CrystalDiskInfo#183]
My disk (Toshiba 128G3A) is not found.

![image](https://user-images.githubusercontent.com/80272847/179778799-03d77900-9fe3-4c1e-9706-c510e3ea8f7f.png)

**Comment by hiyohiyo** [comment]
Please attach the text copy (Edit > Copy) and DiskInfo.log.
https://crystalmark.info/en/software/crystaldiskinfo/crystaldiskinfo-contact/

**Comment by luimen6** [comment]
I attached you the both logs.
Please let me know if you need further information.
[Crystaldisk.txt](https://github.com/hiyohiyo/CrystalDiskInfo/files/9147415/Crystaldisk.txt)
[DiskInfo64.log](https://github.com/hiyohiyo/CrystalDiskInfo/files/9147416/DiskInfo64.log)

**Comment by hiyohiyo** [comment]
Sorry, CrystalDiskInfo does not support SD Memory Card and eMMC SSD.

Toshiba 128G3A may be connected by SD Memory or eMMC interface.
