### ISSUE TITLE
Error: Disk not found

### ISSUE THREAD

**Issue by luimen6** [hiyohiyo/CrystalDiskInfo#184]
My disk Sandisk is not found.
[DiskInfo64.log](https://github.com/hiyohiyo/CrystalDiskInfo/files/9161012/DiskInfo64.log)

**Comment by hiyohiyo** [comment]
Sorry, CrystalDiskInfo does not support SD Memory Card and eMMC SSD.

SanDisk DA4064 may be connected by SD Memory or eMMC interface.
