### ISSUE TITLE
New disk bad with available spare 64. Doesn't match AIDA64.

### ISSUE THREAD

**Issue by einzel** [hiyohiyo/CrystalDiskInfo#186]
I'm afraid I don't know enough about this to point out where the problem is, but from my perspective, there seems to be one.

This drive has been running for a couple of days so far. I loaded up CrystalDiskInfo to check on my SATA HDDs that are currently maxxing their reads for a while doing some backups. Then I saw a lot of red on the 980 Pro. Help?

![weird SMART data](https://user-images.githubusercontent.com/58613827/189246090-d46dc92d-afd5-4696-94ae-32ce2a3c9857.PNG)

**Comment by hiyohiyo** [comment]
CrystalDiskInfo may not get correct SMART data or Your Samsung SSD 980 PRO returns storange data.
"Available Spare Threshold" value is 255 which is reserved value and "Percentage Used" reaches 255 which is vendor specific estimate of the percentage of NVM subsystem life...

A workaround has been added for cases where the "Available Spare Threshold" value is greater than 100.
https://crystalmark.info/download/zz/CrystalDiskInfo8_17_8.zip

<img width="367" alt="image" src="https://user-images.githubusercontent.com/3816714/193434778-bfd49add-1803-486b-bbab-d1450ddf86df.png">
https://nvmexpress.org/wp-content/uploads/NVM-Express-1_3d-2019.03.20-Ratified.pdf
