### ISSUE TITLE
Seems does not support WD blue 3d ssd's S.M.A.R.T?

### ISSUE THREAD

**Issue by XZiar** [hiyohiyo/CrystalDiskInfo#19]
I am using the latest version 8.0.0, while most attribute of my SSD (WD blue 3D NAND SSD) shows "Vendor Specific".
![image](https://user-images.githubusercontent.com/15145384/51271839-6ce40500-197d-11e9-97d5-c7032722d8f7.png)

I find their corresponding name in WD's toolkit software, maybe you can add them in the future?
![image](https://user-images.githubusercontent.com/15145384/51271970-bb919f00-197d-11e9-944e-31730f851d54.png)
![image](https://user-images.githubusercontent.com/15145384/51272004-c9472480-197d-11e9-8091-dcd9c12723e3.png)
![image](https://user-images.githubusercontent.com/15145384/51272019-d3692300-197d-11e9-895c-3897f4b3ffd6.png)

**Comment by hiyohiyo** [comment]
CrystalDiskInfo 8.8.0 Alpha2 supports WD SATA SSDs.
