### ISSUE TITLE
SMART info only shown in English when Simplified Chinese is selected.

### ISSUE THREAD

**Issue by maidmeow4** [hiyohiyo/CrystalDiskInfo#190]
After upgrading to 8.17.11, one of my disks' SMART info only shown in English, selecting other languages (for example, Traditional Chinese) the SMART info is shown in the correct language.

![图片](https://user-images.githubusercontent.com/8447650/202611589-beaac268-ce2b-4826-8c66-1e1a5cec93e5.png)
----
![图片](https://user-images.githubusercontent.com/8447650/202611771-701c47f4-9f81-46b9-a5d2-2b4e3bd7f15a.png)

**Comment by hiyohiyo** [comment]
A part of Simplified Chinese does not translated.
I would like you to translate untranslated sesction.
