### ISSUE TITLE
0% Health on a brand new SSD

### ISSUE THREAD

**Issue by NekomataGami** [hiyohiyo/CrystalDiskInfo#191]
I recently bought this new SSD and CrystalDiskInfo is reading it as 0% health, I tried other disk monitoring software and its actually on 100% health. 
![image_1](https://user-images.githubusercontent.com/31979501/203022816-78cfc8b7-e17c-4bc4-ad65-3f3c5f204eee.png)

**Comment by hiyohiyo** [comment]
Thank you for bug report.
I would like you to send the result of File > Save (text).

**Comment by NekomataGami** [comment]
> Thank you for bug report. I would like you to send the result of File > Save (text).

Here's the text file.

[CrystalDiskInfo_20221122005204.txt](https://github.com/hiyohiyo/CrystalDiskInfo/files/10058475/CrystalDiskInfo_20221122005204.txt)

**Comment by hiyohiyo** [comment]
I fixed this problem in 8.17.13.
