### ISSUE TITLE
CrystalDiskInfo Can't See Disks That CrystalDiskMark Can See?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [hiyohiyo/CrystalDiskInfo#195]
CrystalDiskInfo Can't See Disks That CrystalDiskMark Can See?

I have 4 disks in a USB 2.0 to SATA enclosure, drives T, U, V, W.  It seems odd that DiskInfo can't see all of them, but DiskMark can?  The 4 disks are 500GB identical size and manufacturer, and as I recall even the same firmware image.  They were taken out of an old RAID tower.  I would think that DiskInfo would see none or all of them, but it only sees half, 2 of 4?

![CrystalDiskInfo Bug Not All Drives Seen](https://user-images.githubusercontent.com/96628648/209041275-5eac621f-ad14-417e-acab-da6f13e26ebc.png)

![image](https://user-images.githubusercontent.com/96628648/209041818-56f023de-b8b5-4256-be03-af1dccc44ce8.png)

Oh, and my name is a gamer tag/handle, I am not Japanese, but German.  I get asked that a lot on GitHub.  If you need any additional information, or more details, just let me know.  I am familiar with programming and various tools, so I suspect your will need some detailed diagnostic information?  Systems is Windows 11, fully patched as of this date.  But any information you may need, just let me know.

![image](https://user-images.githubusercontent.com/96628648/209044181-339305ad-9fa8-4655-b7ad-7867ea2ff8ff.png)

**Comment by hiyohiyo** [comment]
CrystalDiskInfo detects USB HDD using special command (SCSI ATA TRANSLATION).
But old USB enclosure does not support special command, so CrystalDiskInfo can not show a part of USB-HDDs.
