### ISSUE TITLE
LICENSE.txt needs the end-year updated

### ISSUE THREAD

**Issue by jpluimers** [hiyohiyo/CrystalDiskInfo#198]
<https://github.com/hiyohiyo/CrystalDiskInfo/blob/master/LICENSE.txt> has the end-year 2020, whereas <https://github.com/hiyohiyo/CrystalDiskInfo/commits/master> indicates the last commit was in 2022, so the year needs to be updated in `LICENSE.txt`.

**Comment by hiyohiyo** [comment]
Thank you for your report.
I fixed it.
