### ISSUE TITLE
How to change AtaSmart in CrystalDiskInfo to DLL and call it to VB or C #

### ISSUE THREAD

**Issue by zyyujq** [hiyohiyo/CrystalDiskInfo#202]
Just get the disk model and serial number. How to simplify AtaSmart in CrystalDiskInfo and plan it as a simple DLL library so that VB or C # can call it.

**Comment by hiyohiyo** [comment]
There are plans to release a DLL version.
However, we have not determined when we will be able to release it.

**Comment by ftyszyx** [comment]
I wrapped CrystalDiskInfo into a DLL. Now, other languages or Windows applications can also accurately distinguish the disk serial number with the help of CrystalDiskInfo. I have open-sourced this project on GitHub. If you are interested in it, you can check it out and use it.
https://github.com/ftyszyx/CrystalDiskInfo_dll_lib

**Comment by chmichael** [comment]
You should add the version of the CrystalDiskInfo included in the dll and release page.

**Comment by ftyszyx** [comment]
@chmichael ok,I will add it
