### ISSUE TITLE
WD blue 3D NAND SSD support

### ISSUE THREAD

**Issue by hiyohiyo** [hiyohiyo/CrystalDiskInfo#21]
![51271970-bb919f00-197d-11e9-944e-31730f851d54](https://user-images.githubusercontent.com/3816714/52270265-c12e4380-2983-11e9-8ba4-6ad6a0ac5e03.png)
![51272004-c9472480-197d-11e9-8091-dcd9c12723e3](https://user-images.githubusercontent.com/3816714/52270336-081c3900-2984-11e9-8e8e-5c261b91571c.png)
![51272019-d3692300-197d-11e9-895c-3897f4b3ffd6](https://user-images.githubusercontent.com/3816714/52270340-0b172980-2984-11e9-8686-e48e807aeda2.png)

**Comment by krrr** [comment]
It seems that WD blue 3d and SanDisk ultra 3d are the same

http://www.thessdreview.com/our-reviews/wd-blue-3d-ssd-sandisk-ultra-3d-ssd-review-1tb-twins-at-their-finest/2/
![1TB-WD-Blue-3D-SSD-CDI-654x768](https://user-images.githubusercontent.com/5585684/58020615-38ef3b00-7b3b-11e9-9cbc-a872c75ce347.png)
![1TB-SanDisk-Ultra-3D-CDI-656x768](https://user-images.githubusercontent.com/5585684/58020620-3ab8fe80-7b3b-11e9-81ee-3a25a8f96f62.png)

**Comment by hiyohiyo** [comment]
CrystalDiskInfo 8.8.0 Alpha2 supports WD/SanDisk SATA SSDs.
