### ISSUE TITLE
Feature request : For Detect CMR or SMR !

### ISSUE THREAD

**Issue by TP555** [hiyohiyo/CrystalDiskInfo#212]
Hi

Can you may add a Detection if an HDD use CMR or this bad SMR  ?

**Comment by hiyohiyo** [comment]
Unfortunately, in order to distinguish between CMR and SMR, we need to build our own database for each product.
This seems to be difficult in reality, as CMR and SMR are sometimes mixed even for the same model number.

**Comment by lorand-horvath** [comment]
An excellent resource for finding out which model is CMR or SMR has been, for a while now, the HDD Platter Database https://rml527.blogspot.com
