### ISSUE TITLE
Feature request : For Detect TLC or QLC  !

### ISSUE THREAD

**Issue by TP555** [hiyohiyo/CrystalDiskInfo#213]
Hi

Can you may add a Detection if an SSD/M2/NvmE have TLC or the Bad QLC Nand  ?

**Comment by hiyohiyo** [comment]
Unfortunately, in order to distinguish between TLC and QLC, we need to build our own database for each product.
This seems to be difficult in reality, as TLC and QLC are sometimes mixed even for the same model number.
