### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by jsakamoto** [hiyohiyo/CrystalDiskInfo#3]
What is the license for this code?

Can I fork this product and reproduce/redistribute it?

**Comment by hiyohiyo** [comment]
> What is the license for this code?
The MIT license.
I update [README.md](https://github.com/hiyohiyo/CrystalDiskInfo/blob/master/README.md) now.

> Can I fork this product and reproduce/redistribute it?
Yes, please.

**Comment by jsakamoto** [comment]
Thanks, I understood.
