### ISSUE TITLE
How can I know the info showed by the software is correct

### ISSUE THREAD

**Issue by tlsalex** [hiyohiyo/CrystalDiskInfo#85]
Is there a database for every major hard drive in your software , otherwise how can we know the info is correct ?

I read a post on the internet , it says, the big hard drive company,when they develop a new hard drive, before they publish to the market , they will submit SMART info to SMARTCTL tools , so the SMARTCTL tools can recognize the hard drive quite well.

it's that true ? if it's true , do you have a database ? if there is no item to match a unknow hard drive , what info it will display ?

As I want to confirm my hard drive info is correct as bellow.
![APPLE HDD](https://user-images.githubusercontent.com/36788337/93586499-f9f52200-f9da-11ea-89af-58cac0381c90.PNG)

**Comment by hiyohiyo** [comment]
CrystalDiskInfo is only one HDD's S.M.A.R.T. database.
Because almost HDDs have same S.M.A.R.T. attributes. 

Please read CdiResource/language/English.lang

But, SSD's S.M.A.R.T. attributes is variously.
