### ISSUE TITLE
Hiyohiyo, how to get insert hard disk to get USB interface is 3.0 or 2.0？

### ISSUE THREAD

**Issue by lwei2** [hiyohiyo/CrystalDiskInfo#88]
Hiyohiyo, I have a problem: calculate the protocol version of the USB interface inserted into the hard disk, and decide whether it is 3.0 or 2.0. Do you have any good ways to solve this problem?

**Comment by hiyohiyo** [comment]
Unfortunately, I have no idea.
CrystalDiskInfo does not support to USB version detection.

**Comment by lwei2** [comment]
> Unfortunately, I have no idea.
> CrystalDiskInfo does not support to USB version detection.

Thank you so much.
