### ISSUE TITLE
Unnecessary warning tone and yellow indication with Kingston SA4000 480GB SSD.

### ISSUE THREAD

**Issue by D4n2020** [hiyohiyo/CrystalDiskInfo#90]
Happening when SSD has temperature of 51°C. warning sound plays and yellow indication of temperature, but 51°C is totally fine temperature for SSDs.

**Comment by hiyohiyo** [comment]
The temperature threshold value for SSD of latest version is 60℃.
You can customize the threshold for "Menu > Function > Advanced Feature > Alarm - Temperature" or "Temperature Button".

**Comment by hiyohiyo** [comment]
The temperature threshold value for SSD of latest version is 60℃.
You can customize the threshold for "Menu > Function > Advanced Feature > Alarm - Temperature" or "Temperature Button".
